name: Deploy

on:
  push:
    branches: ["develop"]

jobs:
  lint:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      - name: Lint php code
        run: php -l `find *.php`

  push:
    needs: lint
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Build php service
        run: docker compose build php

      - name: Push onto Docker Hub
        run: docker compose push php
